CREATE TABLE credit_card_transactions (
    Time NUMERIC,
    V1 NUMERIC, V2 NUMERIC, V3 NUMERIC, V4 NUMERIC, V5 NUMERIC,
    V6 NUMERIC, V7 NUMERIC, V8 NUMERIC, V9 NUMERIC, V10 NUMERIC,
    V11 NUMERIC, V12 NUMERIC, V13 NUMERIC, V14 NUMERIC, V15 NUMERIC,
    V16 NUMERIC, V17 NUMERIC, V18 NUMERIC, V19 NUMERIC, V20 NUMERIC,
    V21 NUMERIC, V22 NUMERIC, V23 NUMERIC, V24 NUMERIC, V25 NUMERIC,
    V26 NUMERIC, V27 NUMERIC, V28 NUMERIC,
    Amount NUMERIC,
    Class INTEGER
);

SELECT class, COUNT(*) AS total_tranzactions, 
ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM credit_card_transactions), 3) AS foiz
FROM credit_card_transactions
GROUP BY class;
